version: "3"
services:
  ximera:
    build:
      context: .
      dockerfile: Dockerfile-compose
    ports:
      - "2000:2000"
    links:
      - redis
      - mongo
    environment:
      - PORT=2000
      - XIMERA_MONGO_URL=mongo
      - XIMERA_REDIS_URL=redis
      - XAPI_URL=http://lrsqldb:8080
      - XAPI_USERNAME=my_key
      - XAPI_PASSWORD=my_secret
    volumes:
      - repos:/usr/var/server/repositories
      - gpg:/root/.gnupg
  redis:
    image: redis
    ports:
      - "6379:6379"
  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_DATABASE=ximera
    volumes:
      - mongodata:/data/db
    ports:
      - "27017:27017"
  lrsqldb:
    image: yetanalytics/lrsql
    environment:
      - LRSQL_API_KEY_DEFAULT=my_key
      - LRSQL_API_SECRET_DEFAULT=my_secret
      - LRSQL_ADMIN_USER_DEFAULT=my_username
      - LRSQL_ADMIN_PASS_DEFAULT=my_password
      - LRSQL_DB_NAME=db/lrsql.sqlite.db
    volumes:
      - lrsqldb:/lrsql/db
    ports:
      - "8080:8080"
volumes:
  repos:
  gpg:
  mongodata:
  lrsqldb:
